import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import SideBar from "./_components/(containers)/SideBar";
import MainContainer from "./_components/(containers)/MainContainer";
import { Providers } from "@/redux/Provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="ltr">
      <head>
        <meta charSet="UTF-8" />
        <title>Share your Ideas | KalaKawa</title>
        <link rel="icon" href="/crow.png" type="image/x-icon" sizes="16x16" />
        {/* <link rel="stylesheet" href="style.css"> */}
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        /> */}
        <link
          href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <Providers>
          <SideBar></SideBar>
          <MainContainer>{children}</MainContainer>
        </Providers>
        {/* <div className="one"></div> */}
      </body>
    </html>
  );
}
